version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_techfactory

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  root
      MYSQL_DATABASE: techfactory_db
      MYSQL_USER: mi82
      MYSQL_PASSWORD: root

    ports:
      - "3307:3306"
    volumes:
      - dados_mysql:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - rede_techfactory

volumes:
  dados_mysql:

networks:
  rede_techfactory:
    driver: bridge